version: '3'
services:
  client:
    build:
      context: ./
      dockerfile: ./docker/client/Dockerfile   
    container_name: client 
    ports:
      - 80:3000
    depends_on:
      - server
    volumes:
      - client_node_modules:/usr/src/app/node_modules  
      - ./client:/usr/src/app  
    entrypoint: bash -c "npm run start"
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile   
    container_name: server 
    env_file:
      - .env
    ports:
      - 4000:3000
    networks:
      - server
    depends_on:
      coinapi:
        condition: service_started
      db:
        condition: service_healthy
        
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules    
    entrypoint: bash -c "npm run start:dev"
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    restart: always
    ports:
      - 3306:3306 
    networks:
      - server
    volumes: 
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 8s
      retries: 10
  coinapi:
    build:
        context: .
        dockerfile: ./docker/api/Dockerfile
    container_name: coinapi 
    networks:
      - server
    ports:
      - 4001:4001
    volumes:
      - ./api:/usr/src/app   

networks:
  server:
    driver: bridge
volumes:
  client_node_modules:
  server_node_modules:  
  db:
    driver: local